library(tidyverse)
library(data.table)
library(janitor)
library(sf)
library(mapview)
library(raster)
library(terra)
library(lubridate)
library(downloader)
library(ncdf4)
library(elevatr)
library(furrr)

source("02_build/03a_heat.R")
source("02_build/03b_drought.R")
source("02_build/03c_precip.R")
source("02_build/03d_whp.R")

source("02_build/03e_elevation_ruggedness.R")
source("")